[tool.poetry]
name = "hangman-python"
version = "0.1.0"
description = ""
authors = ["szabidev <szabi.vojtek@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
random-word = "^1.0.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
